all: quadraticroots.o main.out

quadraticroots.o: quadraticroots.h quadraticroots.c
	gcc -c quadraticroots.c -o quadraticroots.o -lm

main.out: main.c quadraticroots.o
	gcc main.c quadraticroots.o -o main.out -lm

clean:
	rm -f *.o *.out